/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 pikachu.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef, useEffect, use } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    modifiers_applied001: THREE.SkinnedMesh
    root: THREE.Bone
    ['MCH-torsoparent']: THREE.Bone
    ['MCH-foot_ikparentL']: THREE.Bone
    ['MCH-thigh_ik_targetparentL']: THREE.Bone
    ['MCH-foot_ikparentR']: THREE.Bone
    ['MCH-thigh_ik_targetparentR']: THREE.Bone
    ['MCH-hand_ikparentL']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentL']: THREE.Bone
    ['MCH-hand_ikparentR']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentR']: THREE.Bone
  }
  materials: {
    Pikachu: THREE.MeshStandardMaterial
  }
}

type ActionName = 'idle'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Pikachu(props: JSX.IntrinsicElements['group']) {
  const group = useRef<any>()
  const { nodes, materials, animations } = useGLTF('/pikachu.gltf') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)

  useEffect(() => {
    if (actions['idle']) {
      actions['idle'].play()
    }

  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig_2" position={[-2, -2, -0.188]} rotation={[0, 0.2, 0]}>
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <skinnedMesh name="modifiers_applied001" geometry={nodes.modifiers_applied001.geometry} material={materials.Pikachu} skeleton={nodes.modifiers_applied001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pikachu.gltf')
