
import './globals.css'
import { Inter, Audiowide, Ubuntu } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: "--font-inter" })
const audiowide = Audiowide({ weight: '400', subsets: ['latin'], variable: "--font-audiowide" })
const ubuntu = Ubuntu({ weight: '400', subsets: ['latin'], variable: "--font-ubuntu" })
export const metadata = {
  title: 'Chat with Dua Lipa',
  description: 'Generated by Dua Lipa',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${audiowide.variable} ${ubuntu.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  )
}
